/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  docs: [
    "intro",
    {
      type: "category",
      label: "Examples",
      items: [
        "examples/basic",
        "examples/component-tests",
        "examples/explicit-version",
        "examples/browser",
        "examples/firefox",
        "examples/edge",
        "examples/headless",
        "examples/docker-image",
        "examples/env",
        "examples/specs",
        "examples/project",
        "examples/record",
        "examples/quiet",
        "examples/tag-recordings",
        "examples/artifacts",
        "examples/config",
        "examples/config-file",
        "examples/build-app",
        "examples/start-server",
        "examples/start-multiple-servers",
        "examples/wait-on",
        "examples/custom-install-command",
        "examples/command-prefix",
        "examples/custom-test-command",
        "examples/custom-build-id",
        "examples/working-directory",
        "examples/subfolders",
        "examples/yarn-workspaces",
        "examples/custom-cache-key",
        "examples/node-versions",
        "examples/split-install-tests",
        "examples/custom-install",
        "examples/install-cypress-only",
        "examples/timeouts",
      ],
    },
    "more-examples",
  ],
}

module.exports = sidebars
